# Generated by Django 3.0.2 on 2020-02-01 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_postview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='view_count',
        ),
    ]
